routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::match(["GET", "POST"], "/register", function () {
    return redirect("/login");
})->name("register");

// Router web larashop
Route::resource('users', 'UsersController');
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('categories/{id}/delete-permanent', 'CategoryController@deletepermanent')->name('categories.deletepermanent');
Route::resource('categories', 'CategoryController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','avatars'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $a = 1;
        $filterkeyword = $request->get('keyword');
        $status = $request->get('status');
        if ($status) {
            $all_user = User::where('status', $status)->paginate(10);
        } else {
            $all_user = User::paginate(10);
        }
        if ($filterkeyword) {
            if ($status) {
                $all_user = User::where('email', 'like', "%$filterkeyword%")->where('status', $status)->paginate(10);
            } else {
                $all_user = User::where('email', 'like', "%$filterkeyword%")->paginate(10);
            }
        }
        return view('users.index', ['all_user'=>$all_user,'a'=>$a]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("users.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_user = new \App\User;
        $new_user->name = $request->get('name');
        $new_user->username = $request->get('username');
        $new_user->roles = json_encode($request->get('roles'));
        $new_user->phone = $request->get('phone');
        $new_user->address = $request->get('address');
        $new_user->email = $request->get('email');
        $new_user->password = \Hash::make($request->get('password'));
        if ($request->file('avatar')) {
            $file = $request->file('avatar')->store('avatars', 'public');
            $new_user->avatar = $file;
        }
        $new_user->save();
        return redirect()->route('users.create')->with('status', 'User successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', ['user'=>$user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit', ['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->name = $request->get("name");
        $user->roles = json_encode($request->get("roles"));
        $user->status = $request->get("status");
        $user->phone = $request->get("phone");
        $user->address = $request->get("address");
        if ($request->file("avatar")) {
            if ($user->avatar && file_exists(storage_path('app/public/' . $user->avatar))) {
                \Storage::delete('public/'. $user->avatar);
            }
            $file = $request->file('avatar')->store('avatars', 'public');
            $user->avatar = $file;
        }
        $user->save();
        return redirect()->route('users.edit', [$id])->with('status', 'User succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $user = User::findOrFail($id);
        if ($user->avatar && file_exists(storage_path('app/public/' . $user->avatar))) {
            \Storage::delete('public/'.$user->avatar);
        }
        $user->delete();
        return redirect()->route('users.index')->with('status', 'User successfully deleted');
    }
}

resources/views/users/create.blade.php
@extends("layouts.global")
@section("title") Create User @endsection
@section("content")
<div class="col-md-8">
    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif
    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{route('users.store')}}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Nama</label>
            <input class="form-control" type="text" name="name" id="name" placeholder="Fullname">
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" id="username">
            <small class="form-text text-muted">Name in your dashboard</small>
        </div>
        <label for="">Roles</label><br>
        <div class=" form-check form-check-inline ml-3">
            <input class="form-check-input" type="checkbox" value="ADMIN" name="roles[]" id="ADMIN">
            <label class="form-check-label" for="ADMIN">Administrator</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" value="STAFF" name="roles[]" id="STAFF">
            <label class="form-check-label" for="STAFF">Staff</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" value="CUSTOMER" name="roles[]" id="CUSTOMER">
            <label class="form-check-label" for="CUSTOMER">Customer</label>
        </div>
        <div class="form-group mt-2">
            <label for="phone">Phone number</label>
            <input class="form-control" type="text" name="phone" id="phone">
            <small class="form-text text-muted">Nomer Handphone Anda</small>
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <textarea id="address" class="form-control" rows="2" name="address"></textarea>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="avatar" name="avatar">
            <label class="custom-file-label" for="avatar">Avatar Image</label>
        </div>
        <hr class="my-3">
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" id="email" placeholder="user@mail.com">
            <small class="form-text text-muted"></small>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" id="password" placeholder="password">
            <small class="form-text text-muted"></small>
        </div>
        <div class="form-group">
            <label for="password_confirmation">Password Confirmation</label>
            <input class="form-control" type="password" name="password_confirmation" id="password_confirmation"
                placeholder="password confirmation">
            <small class="form-text text-muted"></small>
        </div>
        <input class="btn btn-primary" type="submit" value="Save">
    </form>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.global')
@section('title')
Edit User
@endsection
@section('content')
<div class="col-md-8">
    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif
    <form enctype="multipart/form-data" class="bg-white shadow p-3" action="{{route('users.update', [$user->id])}}"
        method="POST">
        @csrf
        <input type="hidden" value="PUT" name="_method">
        <div class="form-group">
            <label for="name">Nama</label>
            <input class="form-control" type="text" name="name" id="name" placeholder="Fullname"
                value="{{ $user->name }} ">
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" id="username" value="{{ $user->username }}"
                disabled>
            <small class="form-text text-muted">Name in your dashboard</small>
        </div>
        <label for="">Status</label><br>
        <div class="form-check form-check-inline ml-3">
            <input {{$user->status == "ACTIVE" ? "checked" : ""}} class="form-check-input" type="radio" name="status"
                id="active" value="ACTIVE">
            <label class="form-check-label" for="active">Active</label>
        </div>
        <div class="form-check form-check-inline">
            <input {{$user->status == "INACTIVE" ? "checked" : ""}} class="form-check-input" type="radio" name="status"
                id="inactive" value="INACTIVE">
            <label class="form-check-label" for="inactive">Inactive</label>
        </div>

        <br><label class="mt-3" for="">Roles</label><br>
        <div class=" form-check form-check-inline ml-3">
            <input {{in_array("ADMIN", json_decode($user->roles)) ? "checked" : ""}} class="form-check-input"
                type="checkbox" value="ADMIN" name="roles[]" id="ADMIN">
            <label class="form-check-label" for="ADMIN">Administrator</label>
        </div>
        <div class="form-check form-check-inline">
            <input {{in_array("STAFF", json_decode($user->roles)) ? "checked" : ""}} class="form-check-input"
                type="checkbox" value="STAFF" name="roles[]" id="STAFF">
            <label class="form-check-label" for="STAFF">Staff</label>
        </div>
        <div class="form-check form-check-inline">
            <input {{in_array("CUSTOMER", json_decode($user->roles)) ? "checked" : ""}} class="form-check-input"
                type="checkbox" value="CUSTOMER" name="roles[]" id="CUSTOMER">
            <label class="form-check-label" for="CUSTOMER">Customer</label>
        </div>
        <div class="form-group mt-2">
            <label for="phone">Phone number</label>
            <input class="form-control" type="text" name="phone" id="phone" value="{{ $user->phone }} ">
            <small class="form-text text-muted">Nomer Handphone Anda</small>
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <textarea id="address" class="form-control" rows="2" name="address">{{ $user->address }} </textarea>
        </div>
        @if ($user->avatar)
        <img src="{{asset('storage/'.$user->avatar)}}" width="120" /><br>
        <br>
        @else
        <label class="bg-danger text-white pl-1 pr-1" for="">No Avatar</label><br>
        @endif
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="avatar" name="avatar">
            <label class="custom-file-label" for="avatar">Avatar Image</label>
            <small class="form-text text-muted">Abaikan jika tidak ingin mengganti avatar</small>
        </div>
        <hr class="my-3 font-weight-bold">
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" id="email" placeholder="user@mail.com"
                value="{{ $user->email }}" disabled>
            <small class="form-text text-muted"></small>
        </div>
        <input class="btn btn-primary" type="submit" value="Save">
    </form>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.global')
@section('title')
All User
@endsection
@section('content')
@if(session('status'))
<div class="alert alert-success">
    {{session('status')}}
</div>
@endif
<form action="{{route('users.index')}} ">
    <div class="row">
        <div class="col-5">
            <div class="form-group">
                <input class="form-control" type="text" name="keyword" value="{{Request::get('keyword')}}"
                    placeholder="Masukan email untuk filter">
            </div>
        </div>
        <div class="col-7 pt-1">
            <div class="form-check form-check-inline">
                <input {{Request::get('status')=='ACTIVE'?'checked':''}} class="form-check-input" type="radio"
                    name="status" id="ACTIVE" value="ACTIVE">
                <label class="form-check-label" for="ACTIVE">Active</label>
            </div>
            <div class="form-check form-check-inline">
                <input {{Request::get('status')=='INACTIVE'?'checked':''}} class="form-check-input" type="radio"
                    name="status" id="INACTIVE" value="INACTIVE">
                <label class="form-check-label" for="INACTIVE">Inactive</label>
                <button type="submit" class="btn btn-primary">filter</button>
            </div>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive-md">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Username</th>
                        <th scope="col">Email</th>
                        <th scope="col">Avatar</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($all_user as $user)
                    <tr>
                        {{-- <th scope="row">{{ $a++ }} </th> --}}
                        <th scope="row">{{ $user->name }} </th>
                        <td>{{$user->username}} </td>
                        <td>{{$user->email}} </td>
                        <td>
                            @if($user->avatar)
                            <img src="{{asset('storage/'.$user->avatar)}}" width="70px" height="50px" />
                            @else
                            N/A
                            @endif
                        </td>
                        <td>
                            @if($user->status == "ACTIVE")
                            <span class="badge badge-success">
                                {{$user->status}}
                            </span>
                            @else
                            <span class="badge badge-danger">
                                {{$user->status}}
                            </span>
                            @endif
                        </td>
                        <td><a class="btn btn-info text-white btn-sm mb-lg-auto mb-xl-auto mb-md-1"
                                href="{{route('users.edit',[$user->id])}}"><i class="oi oi-pencil"></i></a>
                            <a class="btn btn-sm btn-primary mt-lg-auto mt-md-auto mt-sm-1 mt-xl-auto mb-lg-auto mb-xl-auto mb-md-1"
                                href="{{ route('users.show',[$user->id])}} "><i class="fa fa-info-circle fa-lg"></i></a>
                            <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline"
                                action="{{route('users.destroy', [$user->id])}}" method="POST">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit"
                                    class="btn btn-danger btn-sm mt-lg-auto mt-md-auto mt-sm-1 mt-xl-auto"><i
                                        class="fa fa-trash fa-lg"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=10>
                            {{$all_user->appends(Request::all())->links()}}
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.global')
@section('title')
Detail USer
@endsection
@section('content')
<div class="col-md-8 bg-white shadow rounded">
    <div class="row">
        <div class="col-md-3 text-center bg-primary-darker p-4 ">
            <section style="min-height: 150px">
                @if ($user->avatar)
                <img class="img-fluid rounded-circle" src="{{asset('storage/'. $user->avatar)}}" width="150px" />
                @else
                No Avatar
                @endif
            </section>
            <div class="mt-3">
                <a class="btn btn-info  btn-sm " href="{{route('users.edit',[$user->id])}}"><i
                        class="fa fa-pencil fa-lg"></i></a>
                <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline"
                    action="{{route('users.destroy', [$user->id])}}" method="POST">
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash fa-lg"></i></button>
                </form>
            </div>
        </div>
        <div class="col-md-9">
            <div class="mt-4 mt-lg-2 mt-xl-2 mb-lg-1 mb-xl-1">
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span style="width:100px;" class="input-group-text font-weight-bold"
                            id="inputGroup-sizing-default">Name</span>
                    </div>
                    <input type="text" class="form-control" aria-label="Default"
                        aria-describedby="inputGroup-sizing-default" value="{{$user->name}}" disabled>
                </div>
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span style="width:100px;" class="input-group-text font-weight-bold"
                            id="inputGroup-sizing-default">Email</span>
                    </div>
                    <input type="text" class="form-control" aria-label="Default"
                        aria-describedby="inputGroup-sizing-default" value="{{$user->email}}" disabled>
                </div>
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span style="width:100px; " class="input-group-text font-weight-bold"
                            id="inputGroup-sizing-default">Phone</span>
                    </div>
                    <input type="text" class="form-control" aria-label="Default"
                        aria-describedby="inputGroup-sizing-default" value="{{$user->phone}}" disabled>
                </div>
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span style="width:100px;" class="input-group-text font-weight-bold"
                            id="inputGroup-sizing-default">Address</span>
                    </div>
                    <input type="text" class="form-control" aria-label="Default"
                        aria-describedby="inputGroup-sizing-default" value="{{$user->address}}" disabled>
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <span style="width:100px;" class="input-group-text font-weight-bold">Roles</span>
                    </div>
                    <textarea class="form-control" aria-label="With textarea" rows="3" disabled
                        style="overflow:hidden;resize:none;">@foreach (json_decode($user->roles) as $role)&middot;{{$role}}&#13;&#10;@endforeach</textarea>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection