routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::match(["GET", "POST"], "/register", function () {
    return redirect("/login");
})->name("register");

// Router web larashop
Route::resource('users', 'UsersController');
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('categories/{id}/delete-permanent', 'CategoryController@deletepermanent')->name('categories.deletepermanent');
Route::resource('categories', 'CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected $table = "categories";

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->get('keyword');
        if ($keyword) {
            $categories= Category::where('name', 'like', "%$keyword%")->paginate(10);
        } else {
            $categories = Category::paginate(10);
        }
        return view('categories.index', ['categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $name = $request->get('name');
        $category = new Category();
        $category->name = $request->get('name');
        if ($request->file('image')) {
            $image_path = $request->file('image')->store('category_images', 'public');
            $category->image = $image_path;
        }
        $category->created_by = \Auth::user()->id;
        $category->slug = \Str::slug($name, '-');
        $category->save();
        return redirect()->route('categories.create')->with('status', 'Category successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories = Category::findOrFail($id);
        return view('categories.show', ['categories'=>$categories]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::findOrFail($id);
        return view('categories.edit', ['categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categories = Category::findOrFail($id);
        $name = $request->get('name');
        $categories->name =$request->get('name');
        $categories->updated_by = \Auth::user()->id;
        $categories->slug = \Str::slug($name, '-');
        if ($request->file('image')) {
            if ($categories->image && file_exists(storage_path('app/public/'.$categories->image))) {
                \Storage::delete('public/'. $categories->image);
            }
            $image = $request->file('image')->store('category_images', 'public');
            $categories->image = $image;
        }
        $categories->save();
        return redirect()->route('categories.edit', [$id])->with('status', 'Category succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categories = Category::findOrFail($id);
        $categories->deleted_by = \Auth::user()->id;
        $categories->save();
        $categories->delete();
        return redirect()->route('categories.index')->with('status', 'Category succesfully Trashed');
    }
    public function trash()
    {
        $categories_delete = Category::onlyTrashed()->paginate(10);
        return \view('categories.trash', ['categories_delete'=>$categories_delete]);
    }

    public function restore($id)
    {
        $categories_delete = Category::withTrashed()->findOrFail($id);
        if ($categories_delete->trashed()) {
            $categories_delete->deleted_by = null;
            $categories_delete->save();
            $categories_delete->restore();
        } else {
            return redirect()->route('categories.index')->with('status', 'Category is not in trash');
        }
        return redirect()->route('categories.index')->with('status', 'Category successfully restored');
    }

    public function deletepermanent($id)
    {
        $categories_delete = Category::withTrashed()->findOrFail($id);
        if (!$categories_delete->trashed()) {
            return redirect()->route('categories.index')->with('status', 'Can not delete permanent active category');
        } elseif ($categories_delete->trashed()) {
            if ($categories_delete->image && file_exists(storage_path('app/public/' . $categories_delete->image))) {
                \Storage::delete('public/'.$categories_delete->image);
            }
            $categories_delete->forceDelete();
        }
        return redirect()->route('categories.index')->with('status', 'Category permanently deleted');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.global')
@section('title')
Create Categori
@endsection
@section('content')
<div class="col-md-8">
    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif
    <form action="{{ route('categories.store') }} " method="POST" enctype="multipart/form-data"
        class=" bg-white shadow-sm p-2">
        @csrf
        <div class="form-group">
            <label for="name">Category Name</label>
            <input class="form-control" type="text" name="name" id="name">
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="image" name="image">
            <label class="custom-file-label" for="image">Choose Image</label>
        </div>
        <input type="submit" value="Save" class="btn btn-primary mt-2">
    </form>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.global')
@section('title')
Edit Category
@endsection
@section('content')
<div class="col-md-8">
    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif
    <form action="{{route('categories.update',[$categories->id])}} " method="post" enctype="multipart/form-data"
        class="bg-white p-3 shadow">
        @csrf
        <input type="hidden" name="_method" value="PUT">
        <div class="form-group">
            <label for="name">Category Name</label>
            <input class="form-control" type="text" name="name" id="name" value="{{$categories->name}}">
        </div>
        <div class="form-group">
            <label for="slug">Category Slug</label>
            <input class="form-control" type="text" name="slug" id="slug" value="{{$categories->slug}}">
        </div>
        @if ($categories->image)
        <span>Curent Image</span><br>
        <img src="{{asset('storage/'.$categories->image)}}" width="120px" alt="">
        @endif
        <div class="custom-file mt-2">
            <input type="file" class="custom-file-input" id="image" name="image">
            <label class="custom-file-label" for="image">Choose Image</label>
            <small>Kosongkan jika tidak ingin memngganti gambar</small>
        </div>
        <input type="submit" value="Save" class="btn btn-primary mt-1">
    </form>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.global')
@section('title')
Category List
@endsection
@section('content')
@if(session('status'))
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-warning">
            {{session('status')}}
        </div>
    </div>
</div>
@endif
<div class="row mb-2">
    <div class="col-6">
        <form action="{{ route('categories.index') }} ">
            <div class="input-group">
                <input type="text" class="form-control" aria-describedby="basic-addon2" name="keyword"
                    value="{{Request::get('keyword')}}" placeholder="Filter Berdasarkan Nama Barang">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Filter</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-6">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link active" href="{{route('categories.index')}}">Published</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('categories.trash')}}">Trash</a>
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive-md">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Slug</th>
                        <th scope="col">Image</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $all_categories)
                    <tr>
                        {{-- <th scope="row">{{ $a++ }} </th> --}}
                        <th scope="row">{{ $all_categories->name }} </th>
                        <td>{{ $all_categories->slug }} </td>
                        <td>
                            @if($all_categories->image)
                            <img src="{{asset('storage/'.$all_categories->image)}}" width="70px" height="50px" />
                            @else
                            No Image
                            @endif
                        </td>
                        <td>
                            <a href="{{route('categories.edit',[$all_categories->id])}}"
                                class="btn btn-info btn-sm "><span class="oi oi-pencil"></span></a>
                            <a class="btn btn-sm btn-primary"
                                href="{{route('categories.show',[$all_categories->id])}}"><span
                                    class="fa fa-info-circle fa-lg"></span></a>
                            <form action="{{route('categories.destroy',[$all_categories->id])}}" method="POST"
                                onsubmit="return confirm('Move category to trash?')" class="d-inline">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-danger btn-sm"><span
                                        class="fa fa-trash fa-lg"></span></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=10>
                            {{$categories->appends(Request::all())->links()}}
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

@endsection

resources/views/categories/show.blade.php
@extends('layouts.global')
@section('title')
Detail Category
@endsection
@section('content')
<div class="col-md-8 bg-white shadow rounded">
    <div class="row">
        <div class="col-md-3 text-center bg-primary-darker p-4">
            <section style="min-height:150px;">
                @if ($categories->image)
                <img class="img-fluid rounded-circle" src="{{asset('storage/'.$categories->image)}}" width="150px">
                @endif
            </section>
            <div class="mt-3">
                <a href="{{route('categories.edit',[$categories->id])}}" class="btn btn-info btn-sm"><span
                        class="oi oi-pencil"></span>
                </a>
                <form action="{{route('categories.destroy',[$categories->id])}}" method="POST"
                    onsubmit="return confirm('Move category to trash?')" class="d-inline">
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-danger btn-sm"><span class="fa fa-trash fa-lg"></span></button>
                </form>
            </div>
        </div>
        <div class="col-md-9">
            <div class="mt-4 mt-lg-2 mt-xl-2 mb-lg-1 mb-xl-1">
                {{-- Content --}}
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span style="width:100px;" class="input-group-text font-weight-bold"
                            id="inputGroup-sizing-default">Name</span>
                    </div>
                    <input type="text" class="form-control" aria-label="Default"
                        aria-describedby="inputGroup-sizing-default" value="{{$categories->name}}" disabled>
                </div>
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span style="width:100px;" class="input-group-text font-weight-bold"
                            id="inputGroup-sizing-default">Slug</span>
                    </div>
                    <input type="text" class="form-control" aria-label="Default"
                        aria-describedby="inputGroup-sizing-default" value="{{$categories->slug}}" disabled>
                </div>
                {{-- Content --}}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/categories/trash.blade.php
@extends('layouts.global')
@section('title')
Category List
@endsection
@section('content')
@if(session('status'))
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-warning">
            {{session('status')}}
        </div>
    </div>
</div>
@endif
<div class="row mb-2">
    <div class="col-6">
        <form action="{{ route('categories.index') }} ">
            <div class="input-group">
                <input type="text" class="form-control" aria-describedby="basic-addon2" name="keyword"
                    value="{{Request::get('keyword')}}" placeholder="Filter Berdasarkan Nama Barang">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Filter</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-6">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="{{route('categories.index')}}">Published</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{route('categories.trash')}}">Trash</a>
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive-md">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Slug</th>
                        <th scope="col">Image</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories_delete as $all_categories)
                    <tr>
                        {{-- <th scope="row">{{ $a++ }} </th> --}}
                        <th scope="row">{{ $all_categories->name }} </th>
                        <td>{{ $all_categories->slug }} </td>
                        <td>
                            @if($all_categories->image)
                            <img src="{{asset('storage/'.$all_categories->image)}}" width="70px" height="50px" />
                            @else
                            No Image
                            @endif
                        </td>
                        <td>
                            <a href="{{route('categories.restore',[$all_categories->id])}}"
                                class="btn btn-success btn-sm "><span class="fa fa-refresh fa-lg"></span>
                            </a>
                            <form action="{{route('categories.deletepermanent',[$all_categories->id])}}" method="POST"
                                onsubmit="return confirm('Delete this Category permanently?')" class="d-inline">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-danger btn-sm"><span
                                        class="fa fa-trash fa-lg"></span></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=10>
                            {{$categories_delete->appends(Request::all())->links()}}
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

@endsection